allowed-duplicate-crates = ["syn", "socket2", "windows-sys", "windows-targets", "windows_aarch64_gnullvm", "windows_aarch64_msvc", "windows_i686_gnu", "windows_i686_msvc", 'windows_x86_64_gnu', "windows_x86_64_gnullvm", "windows_x86_64_msvc", "memoffset", "nix", "parking_lot_core", "polling", "redox_syscall", "regex-automata", "regex-syntax", "rustix", "sha2", "bitflags", "block-buffer", "crypto-common", "digest", "event-listener", "event-listener-strategy", "fastrand", "futures-lite", "async-io", "async-lock", "heck", "linux-raw-sys", "arrayvec", "cfg-if", "hermit-abi"]
too-many-arguments-threshold = 10
#
##msrv = "1.75"

allow-unwrap-in-tests = true

## https://doc.rust-lang.org/nightly/clippy/lint_configuration.html#avoid-breaking-exported-api
# We want suggestions, even if it changes public API.
#avoid-breaking-exported-api = false

excessive-nesting-threshold = 16

#max-fn-params-bools = 2

# https://rust-lang.github.io/rust-clippy/master/index.html#/large_include_file
#max-include-file-size = 1000000

# https://rust-lang.github.io/rust-clippy/master/index.html#/large_stack_frames
stack-size-threshold = 512000

#too-many-lines-threshold = 600

# -----------------------------------------------------------------------------

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_macros
#disallowed-macros = [
#    'dbg',
#
#    # 'std::eprint',
#    # 'std::eprintln',
#    # 'std::print',
#    # 'std::println',
#
#    # 'std::unimplemented', # generated by ArrowDeserialize derive-macro :(
#]

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_names
disallowed-names = []

# Allow-list of words for markdown in docstrings https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
doc-valid-idents = [
    "GitHub",
    "GLB",
    "GLTF",
    "iOS",
    "macOS",
    "MessagePack",
    "MiMalloc",
    "NaN",
    "OBJ",
    "OpenGL",
    "PyPI",
    "sRGB",
    "sRGBA",
    "WebGL",
    "WebGPU",
    "WebSocket",
    "WebSockets",
]
