[package]
name = "mount"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
rencfs = "0.14.11"
shush-rs = "0.1.11"
tracing = "0.1.41"
warning = "0.1.0"
tokio = { version = "1.36", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }