@@startuml

box "run.rs"
participant "run_change_password" as rn_chng_pass
end box

box "encryptedfs.rs"
participant "EncryptedFs:passwd" as encfs_passwd
participant "check_structure" as chk_stucture
end box


box "crypto.rs"
participant "derive_key" as der_key
participant "create_read" as cr_read
participant "atomic_serialize_encrypt_into" as atomic_enc_ser
end box

box "bincode\n<<external>>"
participant "deserialize_from" as des_from
participant "serialize_into" as ser_into
end box

rn_chng_pass --> encfs_passwd
encfs_passwd --> chk_stucture
encfs_passwd <-- chk_stucture

encfs_passwd --> des_from : get key salt
encfs_passwd <-- des_from : <<key_salt>>

encfs_passwd --> der_key : <<old_pass>>\n<<cypher>>\n<<key_salt>>
encfs_passwd <-- der_key : <<current key>>

encfs_passwd --> cr_read: get encryption key <<current_key>>
encfs_passwd <-- cr_read: <<encryption_key>>

encfs_passwd --> der_key : <<new-pass>>\n<<cypher>>\n<<key salt>>
encfs_passwd <-- der_key : <<new key>>

encfs_passwd --> atomic_enc_ser: <<new_key>>\n<<cypher>>\n<<encryption_key>>
atomic_enc_ser --> ser_into
atomic_enc_ser <-- ser_into
encfs_passwd <-- atomic_enc_ser



@@enduml