@@startuml

' participant "run.rs" as run_mount
' participant "mount.rs" as mount_handle

box "run.rs" 
participant "run_mount" as rn_mnt
end box
box "mount.rs"
participant "create_mount_point" as cr_mp
end box

box "linux.rs" 
participant "MountPointImpl::new" as mnt_point_impl_new
participant "MountPointImpl::mount" as mnt_point_impl_mount
participant "mount_fuse" as mnt_fuse
participant "EncryptedFsFuse3::new" as enc_fs_fuse3
end box 

box "encryptedfs.rs"
participant "EncryptedFs::new" as enc_fs
participant "ensure_structure_created" as ensure_fs_created
participant "check_structure" as chk_struct
participant "EncryptedFs::ensure_root_exists" as ensure_root
end box 

rn_mnt --> cr_mp
cr_mp --> mnt_point_impl_new
mnt_point_impl_new --> cr_mp
cr_mp --> rn_mnt

rn_mnt --> mnt_point_impl_mount
mnt_point_impl_mount --> mnt_fuse
mnt_fuse --> enc_fs_fuse3
enc_fs_fuse3 --> enc_fs
enc_fs --> ensure_fs_created
opt
    ensure_fs_created --> chk_struct
    chk_struct --> ensure_fs_created
end
ensure_fs_created --> enc_fs
enc_fs --> ensure_root
ensure_root --> enc_fs

enc_fs --> enc_fs_fuse3
enc_fs_fuse3 --> mnt_fuse
mnt_fuse --> mnt_point_impl_mount
mnt_point_impl_mount --> rn_mnt

@@enduml