@@startuml
box "   fuse3\n<<external>>"
participant "open_file" as ext_open_file
end box

box "linux.rs"
participant "EncryptedFsFuse3::open" as open_file
end box 


box "encyrptedfs.rs"
participant "EncryptedFs::get_attr" as get_attr
participant "EncryptedFs::set_len" as set_len
participant "EncryptedFs::open" as open
participant "EncryptedFs::do_with_read_handle" as do_with_read
participant "EncryptedFs::do_with_write_handle" as do_with_write
participant "check_access" as chk_acc
end box 

ext_open_file --> open_file
open_file --> get_attr : <<file_inode>>
open_file <-- get_attr : <<file_attr>>
open_file --> chk_acc : <<file_attr>>
alt file access allowed
open_file <-- chk_acc : true
    opt truncate=true
        open_file --> set_len
        open_file <-- set_len
    end
open_file --> open : <<file_inode>>,<<rw mode>>
    alt read mode true
        open --> do_with_read
        open <-- do_with_read
        opt write mode true 
            open --> do_with_write
            open <-- do_with_write
        end
        open_file <-- open : <<file_handle>>
        ext_open_file <-- open_file : <<file_handle>>
    else neither read nor write mode 
        open_file <-- open 
        ext_open_file <-- open_file : <<Err:EIO>>
    end
else file access not allowed
open_file <-- chk_acc : false
ext_open_file <-- open_file : <<Err:EACCES>>
end 


@@enduml