@@startuml
box "   fuse3\n<<external>>"
participant "read" as ext_read
end box

box "linux.rs"
participant "EncryptedFsFuse3::read" as read
end box 


box "encyrptedfs.rs"
participant "EncryptedFs::exists" as exists
participant "EncryptedFs::is_file" as is_file
participant "EncryptedFs::get_attr" as get_attr
end box 

box "crypto/read.rs"
participant "RingCryptoRead<File>::read" as crypto_read
participant "RingCryptoRead<File>::seek" as crypto_seek
' participant "RingCryptoRead<File>::get_plaintext_len" as get_plaintext_len
participant "decrypt_block!" as macro_decrypt
end box

box "stream_util.rs"
participant "read" as su_read
end box


ext_read --> read : <<file_inode,offset,bytes>>
read --> exists
alt inode exists
    read <-- exists
    read --> is_file 
    alt inode is file
    read <-- is_file
    read --> get_attr : <<file_inode>>
    read <-- get_attr : <<file_attr>>
    read -> read : <<file_attr.size>>
    read --> crypto_seek : <<offset>>
    ' crypto_seek --> get_plaintext_len
    ' crypto_seek <-- get_plaintext_len
    read <-- crypto_seek
    read --> su_read
    su_read --> crypto_read
    crypto_read --> macro_decrypt
    macro_decrypt --> crypto_read
    crypto_read --> su_read
    su_read --> read
    else inode is not a file
    read <-- is_file
    ext_read <-- read: <<Err:EIO>>
    end
else inode does not exist
read <-- exists 
ext_read <-- read : <<Err:EIO>>
end

@@enduml