name: build-and-tests
on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
  workflow_dispatch:



env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # TODO: remove this when we cache the builds

jobs:
  version:
    concurrency:
      group: version-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: xoriors/rencfs/.github/workflows/version_reusable.yaml@main

  build_and_test:
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    name: build and test
    uses: xoriors/rencfs/.github/workflows/build_and_tests_reusable.yaml@main
    secrets: inherit

  package:
    needs: [ version, build_and_test ]
    uses: xoriors/rencfs/.github/workflows/package_reusable.yaml@main
    with:
      upload_artifacts: false
      version: ${{ needs.version.outputs.version }}
    secrets: inherit
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
