name: clippy
on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # TODO: remove this when we cache the builds

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: rustup update

      - name: build
        run: cargo build --release --all-targets --all-features --target x86_64-unknown-linux-gnu

      - name: fmt check
        run: cargo fmt --all -- --check

      - name: check
        run: cargo check --all --target x86_64-unknown-linux-gnu

      - name: clippy
        run: cargo clippy --all-targets --release --target x86_64-unknown-linux-gnu

      - name: java-bridge build
        run: |
          cd java-bridge
          cargo build --release --all-targets --all-features --target x86_64-unknown-linux-gnu

      - name: java-bridge fmt check
        run: |
          cd java-bridge
          cargo fmt --all -- --check

      - name: java-bridge check
        run: |
          cd java-bridge
          cargo check --all --target x86_64-unknown-linux-gnu

      - name: java-bridge clippy
        run: |
          cd java-bridge
          cargo clippy --all-targets --release --target x86_64-unknown-linux-gnu
