name: version
on:
  workflow_call:
    outputs:
      version:
        description: 'Version from Cargo.toml'
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - uses: actions/checkout@v4

      - id: version
        run: |
          version=$( grep '^version\s*=' Cargo.toml | sed 's/version\s*=\s*"\(.*\)"/\1/' | sed 's/^version\s*=\s*//' )
          echo "version = $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
